### PR TITLE
Milestone 4: Filter

### PR DESCRIPTION
**Pull request by HeflerDev**
# Hello Reviewer!

This milestone is a bit tricky but I think I got the core concepts of the React/Redux workflow.

Since I wanted to play a little with Redux, I added a bit of extra feature, the filter dropdown only shows categories that were created.
Also, I want to point out the fact that I didn't follow exactly the structure as PathWright demands, but still did everything inside the proposal of the App.

So, grab a :coffee: and Happy Coding!

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi @HeflerDev :wave: 

* [x] Inside your bookList component, implement a function that handles filtering -**handleFilterChange**, so you can search for a type of book, within the booklist. 
Then pass **handleFilterChange** down to CategoryFilter component [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone4/HandelChangeFilter.png)
* [x]  The function filters books based on filter value from Redux [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone4/FilterBooksBasedOnStoreFilterSelection.png)

It would be nice if you refactor your code. Remove CategoryFilter from App component and render it BookList component. Else you implement **handleFilterChange** in your **App component**

#### That's it make this change, then submit another form for a code review.

#### If you need clarifications, you can reach me on slack @ Inyama, Uchechukwu Henry
### Have a great day :slightly_smiling_face: 

#### ``` Uchechukwu Henry Inyama ```

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @HeflerDev :wave:

__Thank you for implementing most of the changes required by the last reviewer.
However, we still have some issues to fix before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] You added the `Run Tests` section to your Readme, whereas, you do not have any test case(s) in your project. Kindly remove this section of your Readme.
- [x] The `Issues page` and `MIT license` links in your Readme are broken. Kindly fix them.
- [x] The live demo version of your app is not updated with the recent features you implemented. Kindly deploy your recent changes.
- [x] You disabled ESlint for the entire `CategoryFilter.js` component. Kindly remove the global disabling and fix all ESlint warnings/errors.



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hello @HeflerDev  👋

**You've done pretty well here fixing a few issues raised in the previous review. 👌**

However, let's make a couple of changes.

- [x] Following the GitHub workflow please make the development branch the default branch. It's important to keep the repo professional.

- [x] As suggested in the last review, kindly update the live link with the current changes in this branch.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon: 

Hi @HeflerDev, congratulations on your hard work for this project :muscle: The live link has been updated :+1: Gitflow implemented :100: The project now meets all the minimum requirements :smile: 

Kindly go ahead and merge into development :+1: Do not forget to submit the project completion form :1st_place_medal: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Pull request merged**
